# Generated by Django 4.1.3 on 2022-11-03 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_blogpagegalleryimage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BlogPageGalleryImage",
        ),
    ]
